### ISSUE TITLE
Determine what needs to be in notice file

### ISSUE THREAD

**Issue by keith-turner** [apache/incubator-fluo#690]
Need to populate NOTICE file with correct contents and ensure it ends up in tar ball distribution.

**Comment by ctubbsii** [comment]
I think one way we can/should simplify this is that we eliminate any bundled dependencies from our binary distribution. Instead, we can provide a script, or some documentation on what additional libraries they need to add to their classpath to get things working. This reduces the burden on us significantly to maintain legal stuffs, while (at least in the case of the script) minimally impacting users, and at the very least, reduces risk of making bad assumptions about what user already has and what they need us to bring for them.

Eliminating bundled dependencies means we only have to worry about licence/notices for stuff in our project, because that's all we'd be distributing.

**Comment by keith-turner** [comment]
Some useful links

http://www.apache.org/dev/licensing-howto.html
http://www.apache.org/legal/resolved.html

**Comment by mikewalch** [comment]
Dependencies are no longer bundled after the `fetch.sh` script was created for #705 in 9e82f48fa3e0172.

We have a NOTICE file with the text below:
```
Apache Fluo
Copyright 2016 The Apache Software Foundation.

This product includes software developed at
The Apache Software Foundation (http://www.apache.org/).
```

I believe this ticket can be closed.  Does anyone disagree?

**Comment by joshelser** [comment]
> Dependencies are no longer bundled
> I believe this ticket can be closed. Does anyone disagree?

:+1:, gave a quick grep over the code too, and it looks good!

Maybe unrelated (sorry to derail), it looks like the whitespace/formatting on the LICENSE file is off from @keith-turner's original commit f31ce87d. I think it would be nice to have the verbatim copy of the file, although unsure if required (e.g. compare https://github.com/apache/accumulo/blob/master/LICENSE to https://github.com/apache/incubator-fluo/blob/master/LICENSE).

**Comment by mikewalch** [comment]
@joshelser, I created the PR #710 to fix the whitespace issue.

**Comment by joshelser** [comment]
Thanks!

**Comment by mikewalch** [comment]
@keith-turner, can you close this issue as you created it?
