### ISSUE TITLE
Add stream support to Scanners

### ISSUE THREAD

**Issue by keith-turner** [apache/incubator-fluo#867]
It would be really nice if the fluo scanners had methods to return java streams.

**Comment by mikewalch** [comment]
It looks like what is needed for this issue is a `stream()` method should be added to `CellScanner`, `ColumnScanner`, `RowScanner` like below:

```java
public interface RowScanner extends Iterable<ColumnScanner> {

  default Stream<ColumnScanner> stream() {
    return StreamSupport.stream(spliterator(), false);
  }

  default Stream<ColumnScanner> parallelStream() {
    return StreamSupport.stream(spliterator(), true);
  }
}
```

For more information on streams, check out [this stackoverflow question](https://stackoverflow.com/questions/23114015/why-does-iterablet-not-provide-stream-and-parallelstream-methods) and [this tutorial](http://winterbe.com/posts/2014/07/31/java8-stream-tutorial-examples/)
